export const surpriseMePrompts = [
  "A prehistoric beast with an electrical charge running through its spine and spikes, capable of unleashing powerful electric shocks.",
  "A reptilian creature that boasts a cactus-like exterior, using photosynthesis to heal and empower itself.",
  "A feline predator whose paws and tail burn with intense flames, striking fear into the hearts of its opponents.",
  "A sleek fish with a long, powerful dorsal fin that propels it through the water with incredible speed.",
  "An apparitional crystal floating eerily in the air, its ghostly aura harboring powerful, mysterious forces.",
  "A massive ox with powerful horns, capable of smashing through obstacles and fending off predators.",
  "A bat-like creature that soaks up the energy of the sun to fuel its mighty attacks and enhance its strength.",
  "A bird-like creature with razor-sharp, icy wings that can slice through the air and freeze foes in their tracks.",
  "A tiny creature that can stretch its body to incredible lengths, making it nearly impossible to catch.",
  "A small rodent-like creature that can burrow through the ground at high speeds.",
  "A massive, horned creature with a tough hide and an incredibly powerful charge.",
  "A small, fuzzy creature with powerful wings that allow it to hover in mid-air.",
  "A slimy, amphibious creature that can change color to blend in with its surroundings and evade predators.",
  "A creature that appears to be made of living metal, capable of transforming its shape and composition at will.",
  "A gentle giant that uses its enormous strength to protect and care for its young.",
  "A creature that can manipulate the weather to create powerful storms and control the elements.",
  "A tiny being that can stretch its body to incredible lengths, making it nearly impossible to catch.",
  "A small rodent-like being that can burrow through the ground at high speeds.",
  "A massive, horned being with a tough hide and an incredibly powerful charge.",
  "A small, fuzzy being with powerful wings that allow it to hover in mid-air.",
  "A slimy, amphibious being that can change color to blend in with its surroundings and evade predators.",
  "A being that appears to be made of living metal, capable of transforming its shape and composition at will.",
  "A gentle giant that uses its enormous strength to protect and care for its young.",
  "A being that can manipulate the weather to create powerful storms and control the elements.",
  "A sentient plant with vines that can stretch and grab objects from a distance.",
  "A mythical being that can control time and space, said to only reveal itself to those deemed worthy.",
  "A mechanical construct that can transform its shape and possesses a wide array of weapons.",
  "A humanoid being that wields powerful magic and has the ability to summon other beings to fight alongside it.",
  "A mischievous imp-like being that can shape-shift and is known for causing trouble.",
  "A massive, lumbering being with a tough exoskeleton and powerful jaws.",
  "A ghostly apparition that can phase through walls and possesses the ability to possess and control other beings.",
  "A sleek, fast-moving predator with razor-sharp claws and a highly advanced tracking system.",
  "A crystalline being that can refract light and fire off powerful laser beams.",
  "A being that can merge with other creatures to enhance their abilities and form powerful fusions.",
  "A tiny, insect-like being that can manipulate sound waves and create powerful sonic blasts.",
  "A being that can shape-shift into any form it desires and uses this ability to confuse and evade its enemies.",
  "A giant, lumbering being that is covered in a thick layer of impenetrable armor and wields a massive hammer.",
  "A mischievous being that can manipulate gravity and uses this power to play pranks on unsuspecting individuals.",
  "A being with a hard, rocky exterior and an internal furnace that allows it to shoot streams of molten lava at its foes.",
  "A being that can communicate telepathically and has the ability to read the thoughts of others.",
  "A being that can move at incredibly high speeds and leaves behind afterimages that confuse its opponents.",
  "A being that can manipulate plant life and uses this ability to create traps and ensnare its enemies.",
  "A being that can phase in and out of reality, making it nearly impossible to hit with physical attacks.",
  "Yellow mouse-like creature with red cheeks and long tail that resembles a sweet and sour fruit",
  "Pink, fluffy creature that looks like a large, round dessert covered in cream",
  "Green, turtle-like creature with a leaf on its head that looks like a vegetable",
  "Red and white creature with a cone-shaped head and a cherry-like object on its forehead that looks like an ice cream sundae",
  "Brown, bear-like creature with a honeycomb-like pattern on its stomach that resembles a sweet treat",
  "Purple creature that looks like a grape with a leaf on its head",
  "Small, yellow creature with a leaf-like appendage on its head that resembles a fruit",
  "Blue, shell-shaped creature with a pearl-like object on its back that looks like a type of seafood",
  "Green, caterpillar-like creature with a leaf-like appendage on its head that resembles a vegetable",
  "Yellow and orange creature with a long, curved tail that resembles a type of tropical fruit",
  "Pink, pig-like creature with a curly tail that looks like a type of meat",
  "Purple, cat-like creature with a long, curled tail that looks like a type of dessert",
  "Yellow, bird-like creature with a black beak and a tuft of feathers on its head that looks like a type of fruit",
  "Blue, fish-like creature with a fin on its head that looks like a type of seafood",
  "Green, snake-like creature with a leaf-like appendage on its head that resembles a vegetable",
  "Yellow, circular creature with a red top and a black seed-like object in the center that looks like a type of fruit",
  "Green, turtle-like creature with a shell that looks like a type of vegetable",
  "Red, lobster-like creature with pincers and a tail that looks like a type of seafood",
  "Pink, rabbit-like creature with long ears and a flower-like object on its forehead that looks like a type of vegetable",
  "Orange, fox-like creature with large ears and a fluffy tail that looks like a type of fruit",
];
